<x-app-layout>
    <section class="page-hero">
        <div>
            <div class="eyebrow mb-2">Analytics Workspace</div>
            <h1 class="h2 fw-bold mb-2">Reports</h1>
            <p class="mb-0 text-white-50">Generate filtered reports, print layouts, export CSV, and review report history.</p>
        </div>
    </section>

    <div class="card filter-panel no-lift mb-4">
        <div class="card-body p-4">
            <form method="POST" action="{{ route('reports.generate') }}" class="row g-3" data-loading="true">
                @csrf
                <div class="col-lg-4">
                    <label class="form-label fw-semibold">Report Type</label>
                    <select class="form-select" name="report_type" required>
                        @foreach ($reportTypes as $key => $label)
                            <option value="{{ $key }}" @selected(($filters['report_type'] ?? '') === $key)>{{ $label }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="col-sm-6 col-lg-2"><label class="form-label fw-semibold">Date From</label><input class="form-control" type="date" name="date_from" value="{{ $filters['date_from'] ?? '' }}"></div>
                <div class="col-sm-6 col-lg-2"><label class="form-label fw-semibold">Date To</label><input class="form-control" type="date" name="date_to" value="{{ $filters['date_to'] ?? '' }}"></div>
                <div class="col-sm-6 col-lg-2"><label class="form-label fw-semibold">Year</label><input class="form-control" type="number" name="year" value="{{ $filters['year'] ?? '' }}" min="1900" max="2100"></div>
                <div class="col-sm-6 col-lg-2">
                    <label class="form-label fw-semibold">Season</label>
                    <select class="form-select" name="season"><option value="">All</option>@foreach ($seasons as $season)<option value="{{ $season }}" @selected(($filters['season'] ?? '') === $season)>{{ $season }}</option>@endforeach</select>
                </div>
                <div class="col-lg-4">
                    <label class="form-label fw-semibold">Barangay</label>
                    <select class="form-select" name="barangay"><option value="">All Barangays</option>@foreach ($barangays as $barangay)<option value="{{ $barangay }}" @selected(($filters['barangay'] ?? '') === $barangay)>{{ $barangay }}</option>@endforeach</select>
                </div>
                <div class="col-lg-8 d-flex flex-column flex-md-row gap-2 align-items-md-end">
                    <button class="btn btn-primary" type="submit" data-loading-text="Generating...">Generate Report</button>
                    @if ($selected)
                        <button class="btn btn-outline-primary" formaction="{{ route('reports.print') }}" formmethod="GET" type="submit">Printable Layout</button>
                        <button class="btn btn-outline-secondary" formaction="{{ route('reports.export') }}" formmethod="GET" type="submit">Export CSV</button>
                    @endif
                </div>
            </form>
        </div>
    </div>

    @if ($selected)
        <div class="card no-lift mb-4">
            <div class="card-header border-0 py-3"><h2 class="h5 mb-0">{{ $selected }} Results</h2></div>
            @if ($rows->count())
                <div class="table-responsive">
                    <table class="table table-hover mb-0">
                        <thead><tr>@foreach ($columns as $label)<th>{{ $label }}</th>@endforeach</tr></thead>
                        <tbody>@foreach ($rows as $row)<tr>@foreach ($columns as $field => $label)<td>{{ data_get($row, $field) }}</td>@endforeach</tr>@endforeach</tbody>
                    </table>
                </div>
            @else
                <div class="card-body"><div class="empty-state text-center p-5"><div class="h5">No report records found</div><div class="text-muted">Try changing filters.</div></div></div>
            @endif
        </div>
    @endif

    <div class="card no-lift">
        <div class="card-header border-0 py-3"><h2 class="h5 mb-0">Report History</h2></div>
        <div class="table-responsive">
            <table class="table table-hover mb-0">
                <thead><tr><th>Type</th><th>Title</th><th>Generated By</th><th>Date</th><th>Rows</th></tr></thead>
                <tbody>
                    @forelse ($history as $report)
                        <tr><td>{{ $report->report_type }}</td><td>{{ $report->title }}</td><td>{{ $report->generatedBy?->name }}</td><td>{{ $report->created_at }}</td><td>{{ data_get($report->payload, 'row_count', '-') }}</td></tr>
                    @empty
                        <tr><td colspan="5" class="text-center text-muted py-4">No report history yet.</td></tr>
                    @endforelse
                </tbody>
            </table>
        </div>
        <div class="card-body border-top d-flex justify-content-end">{{ $history->links() }}</div>
    </div>
</x-app-layout>